import type { Product, Vendor, AnalyticsData } from "./types"

export const mockVendors: Vendor[] = [
  {
    id: "v1",
    name: "Digital Studio",
    avatar: "/professional-avatar.png",
    bio: "Spesialis template dan desain grafis berkualitas tinggi",
    totalProducts: 24,
    totalSales: 1250,
    rating: 4.8,
    joinedAt: "2024-01-15",
  },
  {
    id: "v2",
    name: "Code Masters",
    avatar: "/developer-avatar.png",
    bio: "Developer profesional dengan pengalaman 10+ tahun",
    totalProducts: 18,
    totalSales: 890,
    rating: 4.9,
    joinedAt: "2024-02-20",
  },
  {
    id: "v3",
    name: "EduPro Academy",
    avatar: "/teacher-avatar.png",
    bio: "Platform edukasi terbaik untuk pembelajaran digital",
    totalProducts: 32,
    totalSales: 2100,
    rating: 4.7,
    joinedAt: "2023-11-10",
  },
]

export const mockProducts: Product[] = [
  {
    id: "p1",
    title: "UI/UX Design System Kit",
    description: "Koleksi lengkap komponen UI untuk desain aplikasi modern dengan 500+ elemen siap pakai",
    price: 299000,
    category: "template",
    image: "/ui-design-kit-modern.jpg",
    vendorId: "v1",
    vendorName: "Digital Studio",
    downloads: 456,
    rating: 4.8,
    createdAt: "2024-10-15",
    fileSize: "125 MB",
  },
  {
    id: "p2",
    title: "E-Commerce Starter Template",
    description: "Template Next.js lengkap untuk toko online dengan dashboard admin dan integrasi payment",
    price: 450000,
    category: "software",
    image: "/ecommerce-website-template.png",
    vendorId: "v2",
    vendorName: "Code Masters",
    downloads: 234,
    rating: 4.9,
    createdAt: "2024-09-20",
    fileSize: "45 MB",
  },
  {
    id: "p3",
    title: "Panduan Lengkap Digital Marketing",
    description: "E-book komprehensif tentang strategi pemasaran digital untuk pemula hingga mahir",
    price: 149000,
    category: "ebook",
    image: "/digital-marketing-ebook-cover.png",
    vendorId: "v3",
    vendorName: "EduPro Academy",
    downloads: 1890,
    rating: 4.7,
    createdAt: "2024-08-10",
    fileSize: "8 MB",
  },
  {
    id: "p4",
    title: "Kursus React & Next.js Mastery",
    description: "Video course 40+ jam untuk menguasai React dan Next.js dari dasar hingga production",
    price: 599000,
    category: "course",
    image: "/programming-course-react-nextjs.jpg",
    vendorId: "v2",
    vendorName: "Code Masters",
    downloads: 567,
    rating: 4.9,
    createdAt: "2024-07-05",
    fileSize: "12 GB",
  },
  {
    id: "p5",
    title: "Social Media Template Pack",
    description: "150+ template Instagram, Facebook & TikTok dalam format Canva dan Figma",
    price: 199000,
    category: "template",
    image: "/social-media-templates-colorful.jpg",
    vendorId: "v1",
    vendorName: "Digital Studio",
    downloads: 2340,
    rating: 4.6,
    createdAt: "2024-11-01",
    fileSize: "320 MB",
  },
  {
    id: "p6",
    title: "Buku Investasi Saham Pemula",
    description: "Panduan lengkap berinvestasi saham untuk pemula dengan strategi yang terbukti",
    price: 89000,
    category: "ebook",
    image: "/stock-investment-book-cover.jpg",
    vendorId: "v3",
    vendorName: "EduPro Academy",
    downloads: 3456,
    rating: 4.8,
    createdAt: "2024-06-15",
    fileSize: "5 MB",
  },
  {
    id: "p7",
    title: "Laravel SaaS Boilerplate",
    description: "Starter kit Laravel dengan multi-tenancy, billing, dan dashboard admin siap pakai",
    price: 750000,
    category: "software",
    image: "/laravel-saas-dashboard.jpg",
    vendorId: "v2",
    vendorName: "Code Masters",
    downloads: 178,
    rating: 4.9,
    createdAt: "2024-10-28",
    fileSize: "85 MB",
  },
  {
    id: "p8",
    title: "Kursus Adobe Illustrator Pro",
    description: "Masterclass lengkap Adobe Illustrator dari pemula hingga mahir dengan 50+ project",
    price: 399000,
    category: "course",
    image: "/adobe-illustrator-course-design.jpg",
    vendorId: "v1",
    vendorName: "Digital Studio",
    downloads: 892,
    rating: 4.7,
    createdAt: "2024-09-12",
    fileSize: "8 GB",
  },
]

export const mockAnalytics: AnalyticsData = {
  totalRevenue: 45670000,
  totalSales: 234,
  totalProducts: 12,
  totalViews: 15670,
  revenueByMonth: [
    { month: "Jul", revenue: 5200000 },
    { month: "Agu", revenue: 6800000 },
    { month: "Sep", revenue: 7500000 },
    { month: "Okt", revenue: 9200000 },
    { month: "Nov", revenue: 8900000 },
    { month: "Des", revenue: 8070000 },
  ],
  salesByCategory: [
    { category: "Template", sales: 89 },
    { category: "Software", sales: 45 },
    { category: "E-book", sales: 67 },
    { category: "Kursus", sales: 33 },
  ],
}
